CREATE TABLE payments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID                                    NOT NULL,
    payer_id        UUID                                    NOT NULL,
    payee_id        UUID                                    NOT NULL,
    amount          DOUBLE PRECISION                        NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    idempotency_key VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_idempotencykey UNIQUE (idempotency_key);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_payeeid UNIQUE (payee_id);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_payerid UNIQUE (payer_id);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_uuid UNIQUE (uuid);
