CREATE TABLE transactions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    payment_id  VARCHAR(255)                            NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    reason      VARCHAR(255)                            NOT NULL,
    executed_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE transactions
    ADD CONSTRAINT uc_transactions_uuid UNIQUE (uuid);

