server:
  port: 8081

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_db
    username: postgres
    password: postgrespassword
  flyway:
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: core-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

# JWT Configuration
jwt:
  secret: c2VjdXJlX3NlY3JldF9rZXlfZm9yX3BheWZsb3dfYXBwbGljYXRpb25fMjAyNA== # Base64 encoded secret key
  expiration: 86400000 # 24 hours in milliseconds

core-service:
  url: http://localhost:8081

