package com.payflow.commons.enums.webhook;

public enum WebhookType {
    FRAUD_TEAM_ALERT,
    MANUAL_DECISION_ALERT,
    CLIENT_NOTIFICATION_APPROVED,
    CLIENT_NOTIFICATION_REJECTED,
    CLIENT_NOTIFICATION_MANUAL_APPROVED,
    CLIENT_NOTIFICATION_MANUAL_REJECTED
}
